name: Rp_Karma
version: 0.0.3
author: John_Willikers
main: com.johnwillikers.rp.Karma
description: This is the punishment/reward system for John Williker's Custom Rp Server.
depend: [Rp_Core]
commands:
  0e812e08h02v8he0182vhe1:
    description: Admits the player into the Karma database
    usage: /0e812e08h02v8he0182vhe1
    permissions: rp.karma.entry
    permission-message: You feel a strong force denying you.
  negate:
    description: GameMaster commands that allows a player to be negated for failRp
    usage: /negate first last offense desc
    permissions: rp.negate
    permission-message: You feel a strong force denying you.
  karma:
    description: GameMaster commands that allows a player to be negated for failRp
    usage: /karma first last
    permissions: rp.karma
    permission-message: You feel a strong force denying you
  gamemaster:
    description: Allows management of Gamemasters
    usage: /gamemaster add first last first last\n/gamemaster remove first last
    permissions: rp.karma
    permission-message: You feel a strong force denying you.
