name: Rp_Mmo
version: 0.0.3
author: John_Willikers
main: com.johnwillikers.rp.Mmo
description: This is the RPG system to the Rp_Package
depend: [Rp_Core]
commands:
  03f9147b09743nf09n71:
    description: Rp_Mmo Entry Command
    usage: /03f9147b09743nf09n71
    permissions: rp.mmo.entry
    permissions-message: You feel a strong force denying you.
  mmo:
    description: let's a gamemaster pull up a users toon sheet
    usage: /mmo (first) (last)
    permissions: rp.mmo.check
    permission-message: You feel a strong force denying you.
  item:
    description: lets you spawn an item needing a type and the weapon id
    usage: /item (type) (id)
    permissions: rp.mmo.item
    permission-message: You feel a strong force denying you.
  character:
    description: lets you view your Character Sheet
    usage: /character
    permissions: rp.mmo.character
    permission-message: Contact a Server Operator.
  level:
    description: Lets you level either a skill or stat
    usage: /level [skill/stat] [name] [amount]
    permissions: rp.mmo.level
    permission-message: Contact a Server Operator.